#!/bin/bash

# Copyright 2019 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BASE_COLLECTION_PATH="/must-gather"

# The following CRDs are not managed by the Maistra operator but it
# will create instances of them.
DEPENDENCY_CRS="jaegers.jaegertracing.io kialis.kiali.io"

# Auxiliary function that adds a k8s prefix to a resource
# $1: The prefix - e.g. "ns" or "pod"
# $2...$N: Resources
# Returns: The list of resources with the prefix prepended on them
#
# Example: addResourcePrefix pod a b c  => Returns: pod/a pod/b pod/c
function addResourcePrefix() {
  local result=""
  local prefix="${1}"
  shift

  for ns in $*; do
    result+=" ${prefix}/${ns} "
  done

  echo "${result}"
}

# Get the namespaces of all control planes in the cluster
function getControlPlanes() {
  local result=()

  local namespaces=$(oc get ServiceMeshControlPlane --all-namespaces -o jsonpath='{.items[*].metadata.namespace}')
  for namespace in ${namespaces}; do
    result+=" ${namespace} "
  done

  echo "${result}"
}

# Get the members of a mesh (namespaces that belongs to a certain control plane).
# $1 = Namespace of the control plane - e.g. "istio-system"
function getMembers() {
  local cp="${1}"

  local output="$(oc -n "${cp}" get ServiceMeshMemberRoll default -o jsonpath='{..members}' 2>/dev/null)"

  if [ -z "${output}" ]; then
    return
  fi

  output="$(echo ${output} | tr '[]' '  ')"

  # The oc get command above returns namespaces surrounded by quotes. Trim any quotes.
  output=$(echo ${output} | sed -e 's/"//g')
  echo ${output}
}

# Get the CRD's that belong to Maistra
function getCRDs() {
  local result=""
  local output=$(oc get crd -lmaistra-version -o jsonpath='{.items[*].metadata.name}')
  for crd in ${output}; do
    result+=" ${crd} "
  done

  # Get the remaining CRD's that don't contain a maistra label. See https://issues.jboss.org/browse/MAISTRA-799
  local output=$(oc get crd -l'!maistra-version' -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep -E 'maistra|istio')
  for crd in ${output}; do
    result+=" ${crd} "
  done

  echo ${result}
}

# getSynchronization dumps the synchronization status for the specified control plane
# to a file in the control plane directory of the control plane namespace
# Arguments:
#		namespace of the control plane
#	Returns:
#		nothing
function getSynchronization() {
  local namespace="${1}"

  echo "Collecting resources for namespace ${cp}"
  local pilotName=$(oc get pods -n ${namespace} -lapp=istiod  -o jsonpath="{.items[0].metadata.name}")

  echo "Overall Envoy synchronization status for namespace ${namespace}" 2>&1 1>${logPath}/controlPlaneStatus
  local logPath=${BASE_COLLECTION_PATH}/namespaces/${namespace}/controlplane
  mkdir -p ${logPath}
  oc exec ${pilotName} -n ${namespace} -c discovery -- /usr/local/bin/pilot-discovery request GET /debug/syncz 2>&1 1>${logPath}/synchronization
}

# getEnvoyConfigForPodsInNamespace dumps the envoy config for the specified namespace and
# control plane to a file in the must-gather directory for each pod
# Arguments:
#   namespace of the control plane
#   namespace to dump
# Returns:
#   nothing
function getEnvoyConfigForPodsInNamespace() {
  local controlPlaneNamespace="${1}"
  local pilotName=$(oc get pods -n ${controlPlaneNamespace} -lapp=istiod  -o jsonpath="{.items[0].metadata.name}")
  local podNamespace="${2}"

  echo "Collecting Envoy config for pods in ${podNamespace}, control plane namespace ${controlPlaneNamespace}"

  local pods="$(oc get pods -n ${podNamespace} -o jsonpath='{ .items[*].metadata.name }')"
  for podName in ${pods}; do
    if [ -z $podName ]; then
        continue
    fi

    if oc get pod -o yaml ${podName} -n ${podNamespace} | grep -q proxyv2; then
      echo "Collecting config for pod ${podName}.${podNamespace}"

      local logPath=${BASE_COLLECTION_PATH}/namespaces/${podNamespace}/pods/${podName}
      mkdir -p ${logPath}

      echo "Pilot config for pod ${podName}.${podNamespace} from istiod ${pilotName}.${controlPlaneNamespace}" 2>&1 1>${logPath}/pilotConfiguration
      oc exec ${pilotName} -n ${controlPlaneNamespace} -c discovery -- bash -c "/usr/local/bin/pilot-discovery request GET /debug/config_dump?proxyID=${podName}.${podNamespace}" 2>&1 1>${logPath}/pilotConfiguration

      echo "Envoy config for pod ${podName}.${podNamespace} from pilot ${pilotName}.${controlPlaneNamespace}" 2>&1 1>${logPath}/envoyConfiguration
      oc exec -n ${podNamespace} ${podName} -c istio-proxy -- /usr/local/bin/pilot-agent request GET config_dump 2>&1 1>${logPath}/envoyConfiguration
    fi
  done
}

function main() {
  echo
  echo "Executing Istio gather script"
  echo

  operatorNamespace=$(oc get pods --all-namespaces -l name=istio-operator -o jsonpath="{.items[0].metadata.namespace}")
  local resources="ns/${operatorNamespace} MutatingWebhookConfiguration ValidatingWebhookConfiguration"


  local controlPlanes="$(getControlPlanes)"
  resources+="$(addResourcePrefix ns ${controlPlanes})"

  for cp in ${controlPlanes}; do
      local members=$(getMembers ${cp})
      resources+="$(addResourcePrefix ns ${members})"
      getSynchronization ${cp}

      for cr in ${DEPENDENCY_CRS}; do
        oc adm inspect "--dest-dir=${BASE_COLLECTION_PATH}" -n ${cp} ${cr}
      done

       #collect Envoy configuration first from control plane pods and then from members
       getEnvoyConfigForPodsInNamespace ${cp} ${cp}
       for member in ${members}; do
           if [ -z $member ]; then
               continue
           fi
          echo "Processing ${cp} member ${member}"
          getEnvoyConfigForPodsInNamespace ${cp} ${member}
       done
  done

  local crds="$(getCRDs)"
  resources+="$(addResourcePrefix crd ${crds})"

  for resource in ${resources}; do
    echo
    echo "Dumping resource ${resource}..."
    oc adm inspect "--dest-dir=${BASE_COLLECTION_PATH}" ${resource}
  done

  # Get all CRD's
  for crd in ${crds}; do
    echo
    echo "Dumping CRD ${crd}..."
    oc adm inspect "--dest-dir=${BASE_COLLECTION_PATH}" --all-namespaces ${crd}
  done

  echo
  echo
  echo "Done"
  echo
}

main
